osx_image: xcode8.2
language: objective-c
before_install:
- gem install cocoapods
- brew install carthage
- carthage bootstrap
script:
- set -o pipefail
- xcodebuild clean build test -project MockSix.xcodeproj -scheme MockSix-macOS | xcpretty
- xcodebuild clean build test -project MockSix.xcodeproj -scheme MockSix-iOS | xcpretty
- xcodebuild clean build test -project MockSix.xcodeproj -scheme MockSix-tvOS | xcpretty
- pod lib lint
