osx_image: xcode8.2
language: objective-c
before_install:
- gem install cocoapods
- brew install carthage
- carthage bootstrap
script:
- set -o pipefail
- xcodebuild clean build test -project MockSix.xcodeproj -scheme MockSix-macOS | xcpretty
- xcodebuild clean build test -project MockSix.xcodeproj -scheme MockSix-iOS -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.2' | xcpretty
- xcodebuild clean build test -project MockSix.xcodeproj -scheme MockSix-tvOS -destination 'platform=tvOS Simulator,name=Apple TV 1080p,OS=10.1' | xcpretty
- pod lib lint
