osx_image: xcode9
language: objective-c
matrix:
  include:
    - os: osx
      before_install:
        - gem install cocoapods
        - brew install carthage
        - carthage bootstrap
      script:
        - set -o pipefail
        - xcodebuild clean build test -project MockSix.xcodeproj -scheme MockSix-macOS | xcpretty
        - xcodebuild clean build test -project MockSix.xcodeproj -scheme MockSix-iOS -destination 'id=85AF1F51-F2EB-4A4D-930B-0E5761511A45' | xcpretty
        - xcodebuild clean build test -project MockSix.xcodeproj -scheme MockSix-tvOS -destination 'id=810495B9-1EB7-43BB-96AF-0A3196C7A3B7' | xcpretty
        - pod lib lint
    - os: osx
      language: generic
      script:
        - mv Support/Package.test.swift Package.swift
        - swift build
        - swift test
    - os: linux
      language: generic
      sudo: required
      dist: trusty
      before_install:
        - . scripts/travis_install_swift_for_ubuntu.sh
      script:
        - mv Support/Package.test.swift Package.swift
        - swift build
        - swift test
notifications:
  email: false
